require 'log'.debug('hello world')
require 'log'.info('hello world')
require 'log'.log('hello world')
require 'log'.warn('hello world')
require 'log'.error('hello world')
require 'log'.panic('hello world')
