#pragma once
#include <glad/glad.h>
namespace firefly::gl {
enum class BUFFER_ATTR {
  ACCESS = GL_BUFFER_ACCESS,
  ACCESS_FLAGS = GL_BUFFER_ACCESS_FLAGS,
  IMMUTABLE_STORAGE = GL_BUFFER_IMMUTABLE_STORAGE,
  MAPPED = GL_BUFFER_MAPPED,
  MAP_LENGTH = GL_BUFFER_MAP_LENGTH,
  MAP_OFFSET = GL_BUFFER_MAP_OFFSET,
  SIZE = GL_BUFFER_SIZE,
  STORAGE_FLAGS = GL_BUFFER_STORAGE_FLAGS,
  USAGE = GL_BUFFER_USAGE
};
};