#pragma once
#include <glad/glad.h>
namespace firefly::gl {
enum class BUFFER_USAGE {
  STATIC_DRAW = GL_STATIC_DRAW,
  STATIC_COPY = GL_STATIC_COPY,
  STATIC_READ = GL_STATIC_READ,
  STREAM_DRAW = GL_STREAM_DRAW,
  STREAM_COPY = GL_STREAM_COPY,
  STREAM_READ = GL_STREAM_READ,
  DYNAMIC_DRAW = GL_DYNAMIC_DRAW,
  DYNAMIC_COPY = GL_DYNAMIC_COPY,
  DYNAMIC_READ = GL_DYNAMIC_READ,
};
}