#pragma once
#include <glad/glad.h>
namespace firefly::gl {
enum class ERROR_TYPE {
  NO_ERROR = GL_NO_ERROR,
  INVALID_ENUM = GL_INVALID_ENUM,
  INVALID_VALUD = GL_INVALID_VALUE,
  INVALID_OPERATION = GL_INVALID_OPERATION,
  INVALID_FRAMEBUFFER_OPERATION = GL_INVALID_FRAMEBUFFER_OPERATION,
  OUT_OF_MEMORY = GL_OUT_OF_MEMORY,
  STACK_UNDERFLOW = GL_STACK_UNDERFLOW,
  STACK_OVERFLOW = GL_STACK_OVERFLOW
};
};