#pragma once
#include <glad/glad.h>
namespace firefly::gl {
enum class MAP_ACCESS_FLAG {
  READ_BIT = GL_MAP_READ_BIT,
  WRITE_BIT = GL_MAP_WRITE_BIT,
  PERSISTENT_BIT = GL_MAP_PERSISTENT_BIT,
  COHERENT_BIT = GL_MAP_COHERENT_BIT,
  INVALIDATE_RANGE_BIT = GL_MAP_INVALIDATE_RANGE_BIT,
  INVALIDATE_BUFFER_BIT = GL_MAP_INVALIDATE_BUFFER_BIT,
  FLUSH_EXPLICIT_BIT = GL_MAP_FLUSH_EXPLICIT_BIT,
  UNSYNCHRONIZED_BIT = GL_MAP_UNSYNCHRONIZED_BIT
};
}