#pragma once
#include <glad/glad.h>
namespace firefly::gl {
enum STORAGE_FLAG {
  DYNAMIC_STORAGE_BIT = GL_DYNAMIC_STORAGE_BIT,
  MAP_READ_BIT = GL_MAP_READ_BIT,
  MAP_WRITE_BIT = GL_MAP_WRITE_BIT,
  MAP_PRESISTENT_BIT = GL_MAP_PERSISTENT_BIT,
  MAP_COHERENT_BIT = GL_MAP_COHERENT_BIT,
  CLIENT_STORAGE_BIT = GL_CLIENT_STORAGE_BIT
};
}